//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationsOfCompanies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class basic_detail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public basic_detail()
        {
            this.business_detail = new HashSet<business_detail>();
            this.dev_bpo_area = new HashSet<dev_bpo_area>();
            this.employee_detail = new HashSet<employee_detail>();
        }
    
        public int basic_id { get; set; }
        public string name { get; set; }
        public int is_company { get; set; }
        public string email_address { get; set; }
        public string mobile_number { get; set; }
        public string phone_number { get; set; }
        public int country_id { get; set; }
        public int province_id { get; set; }
        public int district_id { get; set; }
        public string address { get; set; }
        public string other_details { get; set; }
    
        public virtual country country { get; set; }
        public virtual district district { get; set; }
        public virtual province province { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<business_detail> business_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dev_bpo_area> dev_bpo_area { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee_detail> employee_detail { get; set; }
    }
}
