//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationsOfCompanies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dev_bpo_area
    {
        public int dev_bpo_area_id { get; set; }
        public Nullable<int> basic_ID { get; set; }
        public Nullable<int> AreaID { get; set; }
    
        public virtual basic_detail basic_detail { get; set; }
    }
}
