//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationsOfCompanies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee_skills
    {
        public int employee_skills_id { get; set; }
        public Nullable<int> employee_id { get; set; }
        public Nullable<int> skill_id { get; set; }
    
        public virtual employee_detail employee_detail { get; set; }
        public virtual skill skill { get; set; }
    }
}
