//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationsOfCompanies.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class companies_registrationEntities : DbContext
    {
        public companies_registrationEntities()
            : base("name=companies_registrationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<basic_detail> basic_detail { get; set; }
        public virtual DbSet<business_detail> business_detail { get; set; }
        public virtual DbSet<city> cities { get; set; }
        public virtual DbSet<country> countries { get; set; }
        public virtual DbSet<dev_bpo_area> dev_bpo_area { get; set; }
        public virtual DbSet<district> districts { get; set; }
        public virtual DbSet<employee_detail> employee_detail { get; set; }
        public virtual DbSet<employee_skills> employee_skills { get; set; }
        public virtual DbSet<position> positions { get; set; }
        public virtual DbSet<province> provinces { get; set; }
        public virtual DbSet<ServicesArea> ServicesAreas { get; set; }
        public virtual DbSet<skill> skills { get; set; }
        public virtual DbSet<system_user> system_user { get; set; }
        public virtual DbSet<user_role> user_role { get; set; }
    }
}
