//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationsOfCompanies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class system_user
    {
        public int user_id { get; set; }
        public int role_id { get; set; }
        public string email_id { get; set; }
        public string password { get; set; }
        public Nullable<int> is_active { get; set; }
        public string other_detail { get; set; }
    
        public virtual user_role user_role { get; set; }
    }
}
